@base_url = http://localhost:3000
@authToken = {{Authenticate.response.body.access_token}}

@gabrielCheckingsAccountId = cbad914f-d6d4-445b-96ed-0c83d8322039
@gabrielSavingsAccountId = f8389a1d-8d7b-4946-858c-1b91419e8377

GET {{base_url}}/knex/alive

###

# @name Create_User
POST {{base_url}}/users/create
Content-Type:  application/json

{
  "name": "gsw",
  "login": "gsw@email.com",
  "pin": "0123"
}

###

# @name Authenticate
POST {{base_url}}/auth/authorize
Content-Type:  application/json

{
  "name": "gsw",
  "login": "gsw@email.com",
  "pin": "0123"
}

###

# @name Create_Account
POST {{base_url}}/accounts/open
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "accountName": "Corrente"
}

###

# @name Get_All_Accounts
GET {{base_url}}/accounts
Content-Type:  application/json
Authorization: Bearer {{authToken}}

###

# @name Get_Account_Transactions
GET {{base_url}}/accounts/2202c139-360a-49b9-ac3b-53a632c1a323/transactions
Content-Type:  application/json
Authorization: Bearer {{authToken}}

###

# @name Deposit
POST {{base_url}}/accounts/2202c139-360a-49b9-ac3b-53a632c1a323/deposit
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "amount": 4000
}

###

# @name Withdraw
POST {{base_url}}/accounts/{{gabrielSavingsAccountId}}/withdraw
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "amount": 700
}