@base_url = http://localhost:3000
@authToken = {{Authenticate.response.body.access_token}}

GET {{base_url}}/knex/alive

###

# @name Create_User
POST {{base_url}}/users/create
Content-Type:  application/json

{
  "name": "Gabriel",
  "login": "gabriel@email.com",
  "pin": "0123"
}

###

# @name Authenticate
POST {{base_url}}/auth/authorize
Content-Type:  application/json

{
  "name": "Gabriel",
  "login": "gabriel@email.com",
  "pin": "0123"
}

###

# @name Create_Account
POST {{base_url}}/accounts/open
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "accountName": "Checkings"
}

###

# @name Get_All_Accounts
GET {{base_url}}/accounts
Content-Type:  application/json
Authorization: Bearer {{authToken}}